# Generated by Django 3.2.4 on 2021-06-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210622_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exoplanet',
            name='dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='default_flag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='disc_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_bmasse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_bmasseerr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_bmasseerr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_bmasselim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_bmassj',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_bmassjerr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_bmassjerr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_bmassjlim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_controv_flag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_eqt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_eqterr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_eqterr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_eqtlim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_insol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_insolerr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_insolerr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_insollim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbeccen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbeccenerr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbeccenerr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbeccenlim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbpererr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbpererr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbperlim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbsmax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbsmaxerr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbsmaxerr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_orbsmaxlim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_rade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_radeerr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_radeerr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_radelim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_radj',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_radjerr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_radjerr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_radjlim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='ra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_logg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_loggerr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_loggerr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_logglim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_masserr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_masserr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_masslim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_met',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_meterr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_meterr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_metlim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_rad',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_raderr1',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_raderr2',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_radlim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_teff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_tefferr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_tefferr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_tefflim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_dist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_disterr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_disterr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_gaiamag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_gaiamagerr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_gaiamagerr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_kmag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_kmagerr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_kmagerr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_pnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_snum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_vmag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_vmagerr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_vmagerr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='ttv_flag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
